# Generated by Django 5.1.4 on 2025-05-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterconfig',
            name='password',
        ),
        migrations.RemoveField(
            model_name='masterconfig',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='masterconfig',
            name='password_hash',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
