# Generated by Django 5.1.4 on 2025-05-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_masterconfig_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
